### ISSUE TITLE
Generate API pages for documentation website

### ISSUE THREAD

**Issue by nightlark** [LLNL/Surfactant#109]
Once functions have docstrings, it should be possible to generate API pages for the documentation website -- this will be useful for users looking to use Surfactant as a library. Adding a page with a brief intro to library/programmatic use could also be useful.

**Comment by Moses-Mk** [comment]
Assign me this

**Comment by nightlark** [comment]
As a side note, https://sphinxcontrib-napoleon.readthedocs.io/en/latest/ might be a starting point for a sphinx extension that can be used to generate the API documentation as part of the ReadTheDocs builds. https://stackoverflow.com/questions/74635207/is-there-a-way-automate-sphinx-apidoc-generation-in-readthedocs has some info on how to get the extra sphinx-apidoc command to run as part of RTD builds.

**Comment by nightlark** [comment]
Yea, the module documentation looks right — once the PR is open ReadTheDocs will generate a preview of the updated docs site and we can check for any issues with the automated API docs build job (probably just minor tweaks to commands listed in the .readthedocs.yaml file at that point).

**Comment by Moses-Mk** [comment]
I will be submitting the pull request (PR) today for the recent updates to our documentation. To ensure that everything is in order, please follow these steps to generate the Sphinx documentation page in a Windows environment:

## Instructions to Generate Sphinx Documentation

1. **Open Command Prompt**: Press `Win + R`, type `cmd`, and hit `Enter` to open the Command Prompt.

2. **Navigate to Documentation Directory**: Use the `cd` command to change to the directory where the Sphinx documentation is located. For example:
   ```bash
   cd path\to\your\documentation\directory
   ```

3. **Run the Documentation Build Command**: Type the following command to generate the HTML documentation:
   ```css
   .\make.bat html
   ```

4. **Check the Output**: After the command completes, open the generated HTML files in the `_build\html` directory to review the documentation.

## Review Request

Once I submit the PR, I would appreciate it if you could review it as soon as possible. Your feedback will help us make any necessary corrections quickly so we can merge it before the end of Hacktoberfest on the 31st.

Thank you for your help!

Best,  
Moses Makuei
![image](https://github.com/user-attachments/assets/700d149d-d3c7-41fd-a3c7-deca8e3302d7)
