### ISSUE TITLE
Fuzzing Hash Plugin

### ISSUE THREAD

**Issue by mcutshaw** [LLNL/Surfactant#149]
**Is your feature request related to a problem? Please describe.**
Currently we only have static hashes (SHA256, MD5, etc.), which only allow us to determine absolute matches between BOMs.

**Describe the solution you'd like**
I would potentially be interested in writing a plugin that would generate TLSH, SSDEEP, and similar fuzzy hashes that would folks would be interested in having.

**Describe alternatives you've considered**
We have some other fields that could be used for comparison, but none are quite encompass the whole binary (strings ,etc.).

**Comment by nightlark** [comment]
This could be really useful, particularly if we ever want to capture information about all files in a system (e.g. the chance of two text files being an exact match is low, but maybe a fuzzy hash could hint that a file is very similar to a config file that was previously seen).

**Comment by astrofage** [comment]
Yes this would be super useful as two files might be almost exactly the same just compiled at different times and we would not know.

**Comment by mcutshaw** [comment]
@nightlark So I have this mostly completed, however the only barrier I currently have is that I have to add `BUILD_LIB=1` as an environmental variable when installing this, which I don't know how/if we can do that with poetry/pip. Any ideas?

See https://pypi.org/project/ssdeep/ for context.

**Comment by mcutshaw** [comment]
Currently working on it at https://github.com/mcutshaw/Surfactant/tree/fuzzyhashing

**Comment by nightlark** [comment]
We might just need to include instructions in the README that say to set `BUILD_LIB=1`.

Looking at the ssdeep Python wrapper, it looks like it uses cffi so binary wheels would not be dependent on a specific Python version -- it doesn't look like there is any reason why the Python ssdeep package couldn't provide pre-compiled binary wheels; I'll reach out to the maintainer and see if they are open to a PR that handles building binary wheels and releasing them to PyPI (and asking if the project is still active or looking for maintainers).

**Comment by mcutshaw** [comment]
Closed with 63b6c6c
