### ISSUE TITLE
CycloneDX Error

### ISSUE THREAD

**Issue by REestwick** [LLNL/Surfactant#163]
**Describe the bug**

Upon creation of a CycloneDX JSON SBOM, using Surfactant, it failed validation using the [CycloneDX Web Tool](https://cyclonedx.github.io/cyclonedx-web-tool/validate). 

Upon investigation, it was found that the SBOM had formatting errors regarding to copyright, and a formatting discrepancy in the description and version sections. 

**To Reproduce**

Create an SBOM in CycloneDX format using the Surfactant CLI from [Helics](https://github.com/GMLC-TDC/HELICS/releases). 

**Expected behavior**

SBOM components with the copyright and description formats as follows:

```json
    {
      "copyright": {},
      "description": "",
    }
```

**Screenshots**

![image](https://github.com/LLNL/Surfactant/assets/129106960/c0a3c320-d763-4722-914d-65cc7e220daa)

**System Information**
 - OS: Ubuntu 20.04.

**Example**
[Helics-3.5.1-Linux-x86_64.cdx.json](https://github.com/LLNL/Surfactant/files/14737250/Helics-3.5.1-Linux-x86_64.cdx.json)

**Comment by nightlark** [comment]
Thanks for the bug report!
