### ISSUE TITLE
CVE Binary Tool plugin

### ISSUE THREAD

**Issue by mcutshaw** [LLNL/Surfactant#170]
**Describe the solution you'd like**
Currently I'm not aware of any options we present for version detection or CVE detection. While I would advise against such capability in core Surfactant (do to the risk of false positives), I think it could make a good plugin. Therefore I think a plugin based on using https://github.com/intel/cve-bin-tool would be a fine addition. 

**Describe alternatives you've considered**
None, if you have any good ones please note them.

**Comment by theStache** [comment]
@mcutshaw I'm almost done with this plugin, just working out a few bugs but it should be pushed in a few days.

**Comment by nightlark** [comment]
Resolved by #178
