### ISSUE TITLE
Add file extension identification config options

### ISSUE THREAD

**Issue by nightlark** [LLNL/Surfactant#239]
Add config options for the file type id based on extension to:

- Recognize a list of additional extensions
- Ignore extensions that would typically be recognized

**Comment by KendallHarterAtWork** [comment]
How should the ignore option interact with the "include all" option?  Should all files still be included and a warning issued or should it still exclude those files?  I'm not sure which is more intuitive/useful.

**Comment by nightlark** [comment]
I feel like it would be more useful to have it still exclude those files, since then unknown file types can all be easily included while leaving out a specific set of file types that a user knows they don't care about getting info on (e.g. MS Word Docs, PowerPoints, etc).
