### ISSUE TITLE
Error handling vmlinux files

### ISSUE THREAD

**Issue by Wmyers559** [LLNL/Surfactant#24]
Surfactant crashes with an IndexError when attempting to process linux kernel boot images (vmlinux) as it incorrectly assumes that they are Windows PE files and then fails when processing the non-existent 'optional' header.

To reproduce:
 * run `surfactant generate` on a container that has a linux kernel boot image in COFF format
 
The root cause of this is that `filetypeinfo/id_magic.py` assumes any file with the magic bytes `MZ` is a PE file, when `MZ` really denotes a DOS EXE file, which PE is built off of. The COFF linux boot image format starts with the same `MZ`, but notably is lacking the standard DOS stub of 'This program cannot be run in DOS mode` and does not have the windows-specific 'optional' header. A more robust means of checking for PE files could also check for that message, or for the optional header located after the DOS stub and standard COFF headers.

This is system-agnostic.

**Comment by nightlark** [comment]
Thanks for the detailed bug report! This week is rather busy, but I'll try to get a fix in by the end of next week.

There should also really be a set of test cases malformed files to make sure the different libraries used to handle various file formats don't crash Surfactant.

**Comment by Wmyers559** [comment]
I had spent a little bit of time looking at this, and have a WIP fork where I'm doing some more robust checking of the kernel header itself.
