### ISSUE TITLE
Pypi installer fails if wheel is not installed

### ISSUE THREAD

**Issue by RazerNinjas** [LLNL/Surfactant#25]
If following the instructions in the original readme, the build will fail in a virtual environment if wheel is not installed which then requires the user to manually install wheel before finishing the installation.

**Comment by nightlark** [comment]
Check if the changes in PR #39 resolve the issue on the system that this was failing. I haven't been able to replicate the issue on my own system -- on the system that was having installation troubles, what do you get from running `pip --version` and `python --version`?
