### ISSUE TITLE
Add support for recognizing several library file types (static libraries .a, Windows .lib)

### ISSUE THREAD

**Issue by nightlark** [LLNL/Surfactant#59]
Add support for the magic bytes for static libraries (.a) files used on Linux, and .lib files on Windows.

Some useful references on what the magic bytes are for these files can be found at:
https://github.com/file/file/blob/c8bba134ac1f3c9f5/magic/Magdir/msvc#L22
https://www.garykessler.net/library/file_sigs.html

**Comment by docjon09** [comment]
Hi @nightlark, can I work on this as part of hacktoberfest?

**Comment by nightlark** [comment]
@docjon09 - go for it! As far as files that need changing, the id_magic.py file is the main (probably only) one. Essentially, it will require adding a check that recognizes whatever magic byte pattern the new file types have, then returning a string like “WINDOWS_LIB” or “STATIC_LIB_A” for files that match.

I’d need to check the file formats, but some might have interesting additional metadata for filling in SBOM information — which would involve adding a new file info extractor; if they do I think that could be treated as a separate PR.

**Comment by docjon09** [comment]
Hi @nightlark, I looked into the links shared by you.
In https://www.garykessler.net/library/file_sigs.html, '21 3C 61 72 63 68 3E 0A' is given as the magic number for both UNIX *.ar files and Microsoft *.lib files. 
Also, on [stackoverflow](https://stackoverflow.com/a/41902135), a user said that unix *.a files have the same format as *.ar files so I assume they have the same magic number.

In https://github.com/file/file/blob/c8bba134ac1f3c9f5/magic/Magdir/msvc#L22, I couldn't quite understand what, according to it, the magic number is.

Please verify whether what I've understood is correct.

**Comment by nightlark** [comment]
Resolved by #68.

Thanks @docjon09!
