### ISSUE TITLE
Add output writer plugin for Sourcetrail DB format

### ISSUE THREAD

**Issue by nightlark** [LLNL/Surfactant#72]
Add an output writer plugin (that is optional/requires extra install step) that uses https://github.com/CoatiSoftware/Sourcetraildb (or that looks at the SQLite schema that the library writes to) to output relationships in a file that can be loaded by [Sourcetrail](https://github.com/CoatiSoftware/Sourcetrail/tree/master) for visualization. See https://github.com/quarkslab/pyrrha?tab=readme-ov-file#visualization-with-sourcetrail for an idea of how relationships could be mapped to the Sourcetrail format.

**Comment by nightlark** [comment]
See https://github.com/quarkslab/numbat for writing Sourcetrail DB file.

**Comment by KendallHarterAtWork** [comment]
This issue was addressed by merging #236
